# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='Link for the url')),
                ('url', models.URLField(verbose_name='Destination URL')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Added at')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('hits', models.IntegerField(db_index=True, default=0, editable=False, null=True, verbose_name='Hits')),
                ('language', models.CharField(blank=True, choices=[('he', 'Hebrew'), ('en', 'English')], max_length=5, null=True, verbose_name='Link Language')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
                'ordering': ('-create_date',),
            },
        ),
    ]
