# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 21:31
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_link_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Description'),
        ),
    ]
