# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='Link for the url')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Added at')),
                ('contributor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contriuted by')),
                ('hits', models.IntegerField(db_index=True, default=0, editable=False, null=True, verbose_name='Hits')),
                ('pending', models.BooleanField(db_index=True, default=False, verbose_name='Draft')),
            ],
            options={
                'verbose_name': 'Tip',
                'verbose_name_plural': 'Tips',
                'ordering': ('-create_date',),
            },
        ),
    ]
