# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 09:21
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('tips', '0002_auto_20170507_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
