# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 21:31
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0003_tip_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Content'),
        ),
    ]
